# ============================================================================
# IP ACCESS CONTROL GROUPS
# Settings
# ============================================================================
# This settings document only has effect on 'create' and 'update' actions
#  of this IP-ACG program.
# The 'delete' action is unaffected by this settings document.

# ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
# ip_acgs

# - 'name'
#   - if you specify multiple IP ACGs, make sure you use unique names.
#     - in case of updating an IP ACGs, the program looks up 
#       the id of the existing, targeted IP ACGs, by using their name.

# - 'rules'
#    - specify a maximum of 10 rules per IP ACG.
#    - a single rule can be a *single* IP address (prefix /32),
#      or a *range* of IP addresses (prefix lower than /32). 
#    - set rules smartly using a prefix if you want to 
#      cover multiple IP addresses within one group, e.g., add '/27'.
#      - use https://www.cidr.xyz for a quick insight.
#    - the program will append '/32' to a single IP address, if not done so
#      also. Note that this can cause a duplicate.

# - 'origin'
#    - mainly for your own administration in version control.
#      i.e., which host accessing the directory has this IP address?
#      Add it to 'tags' too if you like (default keeps origin out of tags).

# - Update properties of the suggested IP ACGs that you want to apply 
#   to each AWS directory, below.
#   - An IP ACG id is never specified; 
#     - at creation of new IP ACGs, you do not know it upfront;
#     - at update of current IP ACGs, IP ACGs are matched by name.

# - Add extra ACGs by copy-pasting the suggested items:
#   - each ACG is a new dictionary, indicated by a hyphen, 
#     in the list of 'ip_acgs';
#   - use the same properties as the suggested IP ACGs;
#   - enclose all content with double quotes.
#   - specify 25 IP ACGs at max.

# ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
ip_acgs:

- name: "ThatGroup1"
  desc: "Some description"
  origin: "Security department"
  rules: 
  - "45.33.32.22": "That trusted host"
  - "198.51.100.22/32": "This trusted series of hosts"
  - "198.51.100.22": "This trusted series of hosts"

- name: "ThatGroup1"
  desc: "Some description"
  origin: "Internal control department"
  rules: 
  - "45.33.32.23": "That trusted host"
  - "198.51.100.23/32": "This trusted series of hosts"


# ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
# tags
#
# - Update suggested tag keys and values.
# - Add new tags:
#   - each key-value pair is a new dictionary item;
#   - do not use a hyphen for a new key-value pair;
#   - enclose all content with double quotes.

# ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
tags:

  Application: "WorkSpacesEnv"
  Environment: "test"
  Department: "ThatDepartment"
  CostCenter: "ThatCostCenter"
  CreatedBy: "acgenius"


# ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
# directories
#
# - directories settings are only used for the 'create' action: 
#   - the 'update' action only updates IP ACGs, not directories.
#   - the 'delete' action just deletes IP ACGs. 
#     It will disassociate the IP ACGs from all directories to which they are attached,
#     whatever specified.

# - do you want to apply IP ACGs to *all* of the Active & Registered 
#   WorkSpace directories in your AWS account?
#
#   - yes: set 'id' and 'name' to None.
#   - no (you only want a subset of directories):
#
#     - update the suggested directory below.
#     - if you have more than one directory, add additional directories
#       by copy-pasting the suggested item:
#       - each directory is a new dictionary, indicated by a hyphen, 
#         in the list of 'directories';
#       - use the same properties as the suggested directory below;
#       - enclose all content with double quotes.

# ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
directories:

- id: 
  name: 

# ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
# user_input_validation
# 
# [!] Do not touch if you're not sure what you are doing.

# ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
user_input_validation:  

  ip_address:

    # ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
    # invalid
    # 
    # - Some values do not make sense in IP ACGs.
    # - Update suggested values.
    # - Add new invalid IP addresses:
    #   - each key-value pair is a new dictionary;
    #   - use a hyphen for a new key-value pair;
    #   - enclose all content with double quotes.
    #
    # ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
    invalid:

    - "0.0.0.0": "Open to all"
    - "10.91.0.0": "Private subnet"
    - "127.0.0.1": "Localhost"
    - "255.255.255.0": "Subnet mask"

    # ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
    # prefix
    # 
    # - The prefix (e.g., '/32' in '123.456.789.012/32') 
    #   specifies the number of IP addresses in the range.
    # - Here, the prefix is capped, in order to prevent a user to open up the
    #   WorkSpace directory to an unexpectedly large set of IP addresses.
    # - Play around with it: https://www.cidr.xyz
    # - Update pre-set values.
    # 
    # ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
    prefix:
    
      default: 32  # that is, 1 IP address in your CIDR IP address range
      min: 27  # that is, 32 IP addresses in your CIDR IP address range
    

  # ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
  # ip_acg
  # 
  # - Name length, as well as the number of rules allowed to store in a single IP ACG, 
  #   their descriptions, and the number of IP ACGs are limited by AWS.
  # - Only update suggested values when AWS updates limits.
  #   - ref: https://docs.aws.amazon.com/workspaces/latest/adminguide/amazon-workspaces-ip-access-control-groups.html 
  # 
  # ''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
  ip_acg: 

    name_length:
      max: 50    
    rules_amt:
      max: 10
    rules_desc_length:
      max: 255
    groups_per_directory_amt:
      max: 25
    