# ============================================================================
# IP ACCESS CONTROL GROUPS
# CONFIG
# ============================================================================
# ````````````````````````````````````````````````````````````````````````````
# ip_acgs
#
# - Update properties of the suggested IP ACGs that you want to apply 
#   to each AWS directory, below.
# - Add extra ACGs by copy-pasting the suggested items:
#   - each ACG is a new dictionary, indicated by a hyphen, 
#     in the list of `ip_acgs`;
#   - use the same properties as the suggested IP ACGs;
#   - enclose all string values with double quotes.

# ````````````````````````````````````````````````````````````````````````````

ip_acgs:

- name: "IP ACG 1"
  desc: "Control inbound IP addresses from ACG 1"
  origin: "That Department"
  rule_set: 
  - 123.456.789.012
  - 345.678.901.234
  rule_set_last_modfied: "2025-01-01--12-00-00"

- name: "IP ACG 2"
  desc: "Control inbound IP addresses from ACG 2"
  origin: "That Other Department"
  rule_set: 
  - 567.890.123.456
  - 789.012.345.678
  - 901.234.567.890
  rule_set_last_modfied: "2025-01-02--12-00-00"


# ````````````````````````````````````````````````````````````````````````````
# tags
#
# - Update suggested tag keys and values.
# - Add new tags:
#   - each key: value pair is a new dictionary item;
#   - do not use a hyphen for a new key: value pair;
#   - enclose all string values with double quotes.
# - At runtime, `placeholder` values will be replaced with actual values.

# ````````````````````````````````````````````````````````````````````````````

tags:

  IPACGName: "placeholder"
  Application: "WorkSpacesEnv"
  Environment: "test"
  Department: "ThatDepartment"
  CostCenter: "ThatCostCenter"
  CreatedBy: "IP ACG module"
  ModifiedBy: "IP ACG module"
  Created: "placeholder"
  RuleSetLastApplied: "placeholder"


# ````````````````````````````````````````````````````````````````````````````
# workspace_directories
#
# - Do you want to apply IP ACGs to *all* of the Active & Registered 
#   WorkSpace directories in your AWS account?
#
#   - if yes: leave this setting as-is.
#
#   - if no:
#
#     - update the placeholder directory below.
#     - if you have more than one directory, add additional directories
#       by copy-pasting the suggested item:
#       - each workspace_directory is a new dictionary, indicated by a hyphen, 
#         in the list of `workspace_directories`;
#       - use the same properties as the suggested workspace_directory below;
#       - enclose all string values with double quotes.

# ````````````````````````````````````````````````````````````````````````````

workspace_directories:

- id: 
  name: 

# ````````````````````````````````````````````````````````````````````````````
# user_input_validation
# 
# [!] Do not touch if you're not sure what you are doing.

# ````````````````````````````````````````````````````````````````````````````

user_input_validation:  

  ip_address:

    # ````````````````````````````````````````````````````````````````````````
    # prefix
    # 
    # - The prefix (e.g., `/32` in `123.456.789/012/32`) 
    #   specifies the number of IP addresses within a base IP. 
    # - Here, the prefix is capped in order to prevent a user to open up the
    #   WorkSpace directory to an unexpectedly large set of IP addresses.
    # - Play around with it: https://www.cidr.xyz
    # - Update pre-set values.

    # ````````````````````````````````````````````````````````````````````````
    
    prefix:
      default: 32  # that is, 1 IP address in your CIDR Base IP
      min: 27  # that is, 32 IP addresses in your CIDR Base IP
    
    # ````````````````````````````````````````````````````````````````````````
    # invalid
    # 
    # - Update suggested values.
    # - Add new invalid IP addresses:
    #   - each key: value pair is a new dictionary item;
    #   - do not use a hyphen for a new key: value pair;
    #   - enclose all string values with double quotes.

    # ````````````````````````````````````````````````````````````````````````
    
    invalid:
      0.0.0.0: "Open to all",
      10.91.0.0: "Private subnet",
      127.0.0.1: "Localhost",
      255.255.255.0: "Subnet mask"


  # ``````````````````````````````````````````````````````````````````````````
  # ip_acg_properties
  # 
  # - Name length, as well as the number of IP addresses (rules) allowed to
  #   store in a single IP ACGs, are limited by AWS.
  # - Only update suggested values when AWS updates limits.
  #   - ref: https://docs.aws.amazon.com/workspaces/latest/adminguide/amazon-workspaces-ip-access-control-groups.html 
  # 
  ``````````````````````````````````````````````````````````````````````````
  ip_acg_properties: 

    ip_acg_name_char_length:
      max: 50    
    ip_rules_in_acg_amount:
      max: 10
