# ============================================================================
# IP ACCESS CONTROL GROUPS
# CONFIG
# ============================================================================

# ----------------------------------------------------------------------------
# IP ACGS
# ----------------------------------------------------------------------------

# - Update properties of the IP ACG(s) that you want to apply 
#   to each AWS directory.
# - Add extra ACGs (each ACG a dictionary item, indicated by a hyphen) 
#   by copy-pasting. Use the same properties as a previous item.

ip_acgs:

- name: "IP ACG 1"
  desc: "Control inbound IP addresses from ACG 1"
  origin: "That Department"
  rule_set: 
  - 123.456.789.012
  - 345.678.901.234
  rule_set_last_modfied: 2025-01-01--12-00-00

- name: "IP ACG 2"
  desc: "Control inbound IP addresses from ACG 2"
  origin: "That Other Department"
  rule_set: 
  - 567.890.123.456
  - 789.012.345.678
  - 901.234.567.890
  rule_set_last_modfied: "2025-01-02--12-00-00"

# - Update suggested tags, and/or add new tags.
# - At runtime, `placeholder` values will be replaced with actual values.

tags:

- IPACGName: "placeholder"
  Application: "WorkSpacesEnv"
  Environment: "test"
  Department: "ThatDepartment"
  CostCenter: "ThatCostCenter"
  CreatedBy: "IP ACG module"
  ModifiedBy: "IP ACG module"
  Created: "placeholder"
  RuleSetLastApplied: "placeholder"


# ----------------------------------------------------------------------------
# WORKSPACE DIRECTORIES
# ----------------------------------------------------------------------------
# - Do you want to apply IP ACGs to all your Active & Registered 
# -  WorkSpace directories?
#    - if yes: leave this setting as-is.
#    - if no:
#      - update the placeholder directory below.
#      - if you have more than one directory, add additional directories, 
#        by copy-pasting. Use the same properties as a previous item.

workspace_directories:
- id: 
  name: 


# ----------------------------------------------------------------------------
# APP CONSTRAINTS (ADVANCED)
# ----------------------------------------------------------------------------

# Behaviour of the app.
# - do not touch if you're not sure what you are doing.


input_validation:
# ref: https://www.cidr.xyz for a quick check of impact of `default` and `min`.
- ip_address_prefix:
  default: 32  # that is, 1 IP address in your CIDR Base IP
  min: 27  # that is, 32 IP addresses in your CIDR Base IP


- invalid_user_input:
    0.0.0.0: "Open to all",
    10.91.0.0: "Private subnet",
    127.0.0.1: "Localhost",
    255.255.255.0: "Subnet mask"


# AWS implied limits. 
# Only update when AWS updates limits.
# ref: https://docs.aws.amazon.com/workspaces/latest/adminguide/amazon-workspaces-ip-access-control-groups.html
resource_limits:
  # number of characters
  - ip_acg_name_length:
    max: 50
    
  # number of IP addresses (rules)
  - ip_rules_in_acg_amount:
    max: 10

vpcs_prespecified

